version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: robot
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  web:
    build:
      dockerfile: ./Dockerfile
      context: graphql
#    command: bash -c "cd graphql && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_USERNAME: robot
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    volumes:
      - .:/app:cached
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
volumes:
  postgres_data: {}
networks:
  default:
    name: graphql_default