version: 2.1

jobs:
  build:
    working_directory: ~/stopover-project
    docker:
      - image: cimg/ruby:3.0.4
      - image: cimg/postgres:15.2.0
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - run:
          name: Starting project
          command: |
            cd graphql
            ruby --version
            bundle install
            cp config/database.example.yml config/database.yml
#            rake db:create
#            rake db:schema-load
#            cd ../app
#            npm run generate
#            npm run dev
#            cd ../graphql
#            rails s
#            foreman start
            

workflows:
  backend:
    jobs:
      - build
