version: 2.1
jobs:
  build:
    working_directory: ~/stopover
    docker:
      - image: docker:23.0.5-cli-alpine3.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose run stopover-web rspec
workflows:
  backend:
    jobs:
      - build