version: 2.1

workflows:
  stopover-app-workflow:
    jobs:
      - build

jobs:
  build:
    executor: stopover_stack__ruby_pg_es_redis
    working_directory: ~/stopover/graphql
    # resource_class: 'medium+'
    steps:
      # CHECKOUT
      - checkout:
          path: ~/stopover

      # DEBUG
      - ensure_working_directory

      # DEPENDENCIES
      # - install_system_dependencies
      - install_node_js
      - install_ruby_dependencies

      # DATABASE SETUP
      - wait_for_postgres
      - setup_database

      # RUN TESTS
      - wait_for_opensearch
      - exec_rspec
      - store_test_results:
          path: test/reports

commands:
  # [COMMANDS] DEPENDENCIES

  ensure_working_directory:
    steps:
      - run:
          name: 'Current Working Directory'
          command: |
            pwd
            ls

  install_system_dependencies:
    steps:
      - run:
          name: 'Install Linux Packages'
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B
            sudo apt-get update --allow-releaseinfo-change
            sudo apt-get -y install apt-get install -y build-essential libpq-dev nodejs

  install_ruby_dependencies:
    steps:
      - run:
          name: 'Install bundler'
          command: |
            gem install bundler

      - restore_cache:
          name: 'Restore Gemfile-Cache'
          keys:
            - stopover-graphql-{{ checksum "Gemfile.lock" }}

      - run:
          name: 'Install ruby dependencies'
          command: |
            bundle config set --local path "vendor/bundle"
            bundle install --jobs 4 --retry 3
            bundle clean --force

      - save_cache:
          name: 'Save Gemfile-Cache'
          key: stopover-graphql-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  install_node_js:
    steps:
      - run:
          name: 'Update Node.js and npm'
          command: |
            curl -sSL "https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v20.10.0-linux-x64/bin/node
            sudo npm install -g    npm@latest  # update npm
            sudo npm install -g -f yarn@latest # update yarn
            node -v

  # [COMMANDS] TASKS

  setup_database:
    steps:
      - run:
          name: 'Setup Database'
          command: |
            cp config/database.example.yml config/database.yml
            bin/rails db:create db:schema:load

  exec_rspec:
    steps:
      - run:
          name: 'Rspec'
          command: |
            bin/rake searchkick:reindex:all
            circleci tests glob "./spec/**/*_spec.rb" | \
            circleci tests run --command="xargs timeout 20m bin/bundle exec rspec" --verbose --split-by=timings

  wait_for_postgres:
    steps:
      - run: 'dockerize -wait tcp://localhost:5432 -timeout 1m'

  wait_for_opensearch:
    steps:
      - run: 'dockerize -wait tcp://localhost:9200 -timeout 1m'

images:
  ruby: &_ruby
    image: 'cimg/ruby:3.1.0-browsers'
    environment:
      DATABASE_HOST: 127.0.0.1
      DATABASE_USERNAME: root
      RAILS_ENV: test
      DEEPL_AUTH_KEY: ${DEEPL_AUTH_KEY}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}

  postgres: &_postgres
    image: 'cimg/postgres:15.4'
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: graphql_test
      TZ: 'Europe/Belgrade'

  opensearch: &_opensearch
    image: 'opensearchproject/opensearch:2.7.0'
    environment:
      plugins.security.disabled: 'true'
      transport.host: 'localhost'
      discovery.type: 'single-node'
      cluster.name: 'opensearch'
      ES_JAVA_OPTS: '-Xms1152m -Xmx1152m' # max heap size: 1152 MB

  redis: &_redis
    image: 'cimg/redis:7.0'

executors:
  stopover_stack__ruby_pg_es_redis:
    working_directory: '~/stopover/graphql'
    docker:
      - *_ruby
      - *_postgres
      - *_opensearch
      - *_redis
