version: 2.1
jobs:
  build:
    docker:
      - image: docker:23.0.5-cli-alpine3.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Deps
          command: apk add docker-compose
      - run:
          name: Run Tests
          command: |
            docker-compose up --build -d
            docker-compose run web rspec
workflows:
  backend:
    jobs:
      - build