version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.05
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Run Tests
          command: |
            docker-compose run web rake db:create db:schema:load
            docker-compose up -d
            docker-compose run web rspec
workflows:
  backend:
    jobs:
      - build