version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/ruby:3.0.4
      - image: cimg/postgres:15.2
    steps:
      - checkout
      - run:
          name: Starting project
          command: |
            cd ./graphql
            ruby --version
            bundle install
            rake db:create
            rake db:schema-load
#            cd ../app
#            npm run generate
#            npm run dev
#            cd ../graphql
#            rails s
#            foreman start
            

workflows:
  test-workflow:
    jobs:
      - tests