version: 2.1

jobs:
  tests:
    docker:
      - image: cimg/ruby:3.0.4
      - image: cimg/postgres:15.2
        environment:
          POSTGRES_USER: $GRAPHQL_DATABASE_USERNAME
          POSTGRES_PASSWORD: $GRAPHQL_DATABASE_PASSWORD

    steps:
      - checkout
      - run:
          name: Starting project
          command: |
            cd ./project/graphql
            ruby --version
            bundle install
            cp config/database.example.yml config/database.yml
#            rake db:create
#            rake db:schema-load
#            cd ../app
#            npm run generate
#            npm run dev
#            cd ../graphql
#            rails s
#            foreman start
            

workflows:
  test-workflow:
    jobs:
      - tests