version: '3.8'

services:
  test_adapter:
    build:
      context: test_adapter
    env_file: test_adapter/.env
    ports:
      - "${PORT}:8000"
    networks:
      - shared_network

#  adapter2:
#    build:
#      context: ./adapter2
#    env_file: ./adapter2/.env
#    ports:
#      - "${PORT}:8000"
#    networks:
#      - shared_network

networks:
  shared_network:
    driver: bridge
