default: &default
  adapter: postgresql
  encoding: unicode
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "robot") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: graphql_development
  username: <%= ENV.fetch("DATABASE_USERNAME", "robot") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>

test:
  <<: *default
  database: graphql_test
  username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>

staging:
  <<: *default
  database: graphql_staging
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

production:
  <<: *default
  database: graphql_production
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
