ensure_payments:
  cron: '* * * * *'
  class: 'Workers::EnsurePaymentsJob'
  queue: 'background_payments'
ensure_bookings:
  cron: '* * * * *'
  class: 'Workers::EnsureBookingsPaidJob'
  queue: 'background_payments'
ensure_refunds_status_job:
  cron: '* * * * *'
  class: 'Workers::EnsureRefundsStatusJob'
  queue: 'background_payments'
enqueue_refunds:
  cron: '* * * * *'
  class: 'Workers::EnqueueRefundsJob'
  queue: 'background_payments'
enqueue_payouts:
  cron: '* * * * *'
  class: 'Workers::EnqueuePayoutsJob'
  queue: 'background_payments'
refresh_searchkick_indices_job:
  cron: '0 */2 * * *'
  class: 'Workers::RefreshSearchkickIndicesJob'
  queue: 'searchkick_queue'
generate_sitemap:
  cron: '0 */2 * * *'
  class: 'Workers::GenerateSitemap'
  queue: 'searchkick_queue'
