require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - '**/*.erb'
    - 'vendor/**/*'
    - 'bin/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'lib/templates/**/*'
    - '**/*.md'
    - '**/*.json'
    - 'tmp/**/*'
    - 'storage/**/*'

# CUSTOM COPS

# LAYOUT

Rails/SkipsModelValidations:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/HashAlignment:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

# LINT

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/SafeNavigationConsistency:
  Enabled: false

# METRICS

Metrics/BlockLength:
  Max: 500
  Exclude:
    - 'lib/tasks/*'
    - 'config/routes/*'
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 1000

# RAILS

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/*'
    - 'app/components/**/*'

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/UnknownEnv:
  Environments: development, test, staging, production

# STYLE

Style/GlobalVars:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/ReversibleMigration:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false
